//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazoniamWillowHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public string titulo { get; set; }
        public int idPagina { get; set; }
        public Nullable<int> imagen { get; set; }
    
        public virtual Imagen Imagen1 { get; set; }
        public virtual Pagina Pagina { get; set; }
    }
}
