//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazoniamWillowHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public string titulo { get; set; }
        public int idPagina { get; set; }
        public Nullable<int> imagen { get; set; }
    
        public virtual Imagen Imagen1 { get; set; }
        public virtual Pagina Pagina { get; set; }
    }
}
