//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazoniamWillowHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int Id_Reserva { get; set; }
        public int Id_Habitacion { get; set; }
        public string Cedula_Cliente { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public System.DateTime Fecha_Salida { get; set; }
        public int Id_Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Habitacion Habitacion { get; set; }
    }
}
